name: CI/CD to Docker Hub (HW2)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hw2:latest

      - name: Run container
        run: docker run -d -p 8000:8000 --name test-api ${{ secrets.DOCKERHUB_USERNAME }}/hw2:latest

      - name: Wait for app startup
        run: sleep 10

      - name: Show container status
        run: docker ps -a

      - name: Show container logs
        run: docker logs test-api

      - name: Test health endpoint
        run: curl -f http://localhost:8000/health

      - name: Stop container
        if: always()
        run: docker stop test-api || true